# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.BinaryField(verbose_name='内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modifytime', models.DateTimeField(auto_now=True, null=True, verbose_name='上次修改时间')),
                ('accessory_file', models.CharField(max_length=120, null=True, verbose_name='附件')),
                ('accessory_id', models.IntegerField(null=True, verbose_name='附件id')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.User')),
            ],
        ),
    ]
